version: 2

updates:
  - commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "monthly"

#  - commit-message:
#      include: "scope"
#      prefix: "composer"
#    directory: "/src"
#    labels:
#      - "dependency"
#    open-pull-requests-limit: 10
#    package-ecosystem: "composer"
#    schedule:
#      interval: "monthly"
#    versioning-strategy: "increase"

